name: reinforcement
dependencies:
- python=3.9
- numpy=1.20.3
- matplotlib=3.4
- pandas=1.3.1
- scikit-learn=0.24.2
- pip 
- pip: 
  - pprofile==2.0.2 
  - jsons==0.8.8
  - scipy==1.7.1
  - mdptoolbox-hiive==4.0.3.1
  - gym==0.21.0