name: randomized_optimization
dependencies:
- python=3.9
- numpy=1.20.3
- matplotlib=3.4
- pandas=1.3.1
- scikit-learn=0.24.2
- pip 
- pip: 
  - pprofile==2.0.2 
  - jsons==0.8.8
  - mlrose-hiive==2.2.3